# Generated by Django 3.1.4 on 2021-02-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210225_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='quantity',
            new_name='Cquantity',
        ),
    ]
