# Generated by Django 3.1.4 on 2021-02-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210226_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cartItems',
            field=models.ManyToManyField(blank=True, to='shop.CartProduct'),
        ),
    ]
